# Generated by Django 3.1.1 on 2020-10-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_nome', models.CharField(max_length=30)),
                ('card_descricao_poder', models.CharField(max_length=200)),
                ('card_forca', models.IntegerField(default=1)),
                ('card_agilidade', models.IntegerField(default=1)),
                ('card_resistencia', models.IntegerField(default=1)),
            ],
        ),
    ]
